FROM golang:1.24.4-alpine

# Install required packages
RUN apk add --no-cache iptables iproute2 gcc musl-dev linux-headers git make openssl

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the server 
RUN GOAMD64=v3 go build -v -o vpn-server ./cmd/Server/Server.go && \
    chmod +x vpn-server 

#  certificate directory and generate self-signed certificates for DTLS
RUN mkdir -p /etc/vpn && \
    openssl req -x509 -newkey rsa:4096 -keyout /etc/vpn/server-key.pem -out /etc/vpn/server-cert.pem \
    -days 365 -nodes -subj "/CN=vpn-server" && \
    chmod 600 /etc/vpn/server-key.pem && \
    chmod 644 /etc/vpn/server-cert.pem    

# Expose VPN port
EXPOSE 8080/udp


CMD ["nice", "-n", "-20", "/app/vpn-server"]