FROM golang:1.24.4-alpine

RUN apk add --no-cache iproute2 gcc musl-dev linux-headers curl iputils

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o client ./cmd/Client-VPN/main.go

CMD ["./client"]